version: '24.0'
services:
  frontend:
    build:
      context: ./FrontEnd
    ports:
      - "3000:3000"
    container_name: lp-gas-front

  backend:
    build:
      context: ./BackEnd
    ports:
      - "3001:3001"
    container_name: lp-gas-back
